name: CD

on:
  push:
    tags:
      - v[0-9].[0-9].[0-9]-*

jobs:
  ci:
    name: 'CI'
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/ci.yml
  deployKinsta:
    name: 'Deploy to Kinsta'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: cURL POST
        env:
          KINSTA_TOKEN: ${{ secrets.KINSTA_TOKEN }}
          KINSTA_APP_ID: ${{ secrets.KINSTA_APP_ID }}
        run: |
          curl -i -X POST \
          https://api.kinsta.com/v2/static-sites/deployments \
          -H "Authorization: Bearer $KINSTA_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "static_site_id": "'"$KINSTA_APP_ID"'",
            "branch": "${{  github.ref_name }}"
          }'
  deployVercel:
    name: 'Deploy to Vercel'
    needs: ci
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
