name: CI

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  eslint:
    name: "ESLint"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.2.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.2.0
        cache: 'npm'
    - run: npm install
    - run: npm run lint
  build:
    name: "Build"
    needs: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.2.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.2.0
        cache: 'npm'
    - run: npm install
    - run: npm run build
  codeql:
    name: "CodeQL"
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/codeql.yml
